fixing invocation error.
Due to which my builds are failing. Output of build from github ci/cd

missing from sdist:
  .env
  CODE_OF_CONDUCT.md
  SECURITY.md
  workflows/github-actions.yml
suggested MANIFEST.in rules:
  include *.md
  recursive-include workflows *.yml
ERROR: InvocationError for command /home/runner/work/Second-Brain-Tools/Second-Brain-Tools/.tox/check/bin/check-manifest . (exited with code 1)